[project]
name = "wikidot"
version = "3.0.0a1"
authors = [{ name="ukwhatn", email="ukwhatn@gmail.com" }]
description = "Wikidot Request Library"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
]

dependencies = [
    "httpx ~= 0.25.0",
]

[project.optional-dependencies]
dev = [
    "build",
    "twine",
]

[project.urls]
"Homepage" = "https://github.com/ukwhatn/wikidot.py"
"Bug Tracker" = "https://github.com/ukwhatn/wikidot.py/issues"